config/routes.rb
UUFOM::Application.routes.draw do
  devise_for :users

  get "public/index"

  get "/amazon", :to => redirect("http://www.amazon.com/?_encoding=UTF8&camp=1789&creative=9325&linkCode=ur2&tag=uufom-20")

  root :to => 'public#index'

  resources :admin, :only => [:index]

  resources :upcoming_services, :only => [:create, :update, :destroy]
  resources :events, :only => [:create, :update, :destroy]
  resources :newsletters, :only => [:index, :create]
  resources :social_justice_newsletters, :only => [:index, :create]
  resources :calendars, :only => [:index, :create, :update]
end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
  default_scope order("date ASC")

  def self.upcoming
    where("date >= ?", Date.today)
  end
end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  def file=(attached)
    self.filename     = sanitize(attached.original_filename)
    self.content_type = attached.content_type
    self.data         = attached.read
  end

  private

  def sanitize(filename)
    File.basename(filename).gsub(/[^\w\.\-]/, "_")
  end
end

app/models/social_justice_newsletter.rb
class SocialJusticeNewsletter < ActiveRecord::Base
  def file=(attached)
    self.filename     = sanitize(attached.original_filename)
    self.content_type = attached.content_type
    self.data         = attached.read
  end

  private

  def sanitize(filename)
    File.basename(filename).gsub(/[^\w\.\-]/, "_")
  end
end

app/models/upcoming_service.rb
class UpcomingService < ActiveRecord::Base
  default_scope order("date ASC")

  def self.next
    UpcomingService.where("date >= ?", Date.today).first
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :rememberable
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate_user!

  def index
    @upcoming_services = UpcomingService.where("date >= ?", Date.today)
    @upcoming_service = UpcomingService.new

    @events = Event.upcoming
    @event = Event.new

    @calendar = Calendar.first || Calendar.new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_filter :authenticate_user!, :only => [:create]

  def index
    @calendar = Calendar.first
  end

  def create
    return if params[:calendar].blank?

    @calendar = Calendar.new(params[:calendar])
    @calendar.save!

    Calendar.where("id <> ?", @calendar.id).each(&:destroy)
    redirect_to :back
  end

  def update
    @calendar = Calendar.find(params[:id])
    @calendar.update_attributes(params[:calendar])
    redirect_to :back
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!

  def create
    @event = Event.new(params[:event])
    @event.save!

    redirect_to :back
  end

  def update
    @event = Event.find(params[:id])
    @event.update_attributes(params[:event])
    redirect_to :back
  end

  def destroy
    Event.destroy(params[:id])
    redirect_to :back
  end
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  before_filter :authenticate_user!, :only => [:create]

  def index
    @newsletter = Newsletter.first
    send_data(@newsletter.data, filename: @newsletter.filename,
              type: @newsletter.content_type, disposition: "inline")
  end

  def create
    return if params[:newsletter].blank?

    @newsletter = Newsletter.new
    @newsletter.file = params[:newsletter]

    @newsletter.save!

    Newsletter.where("id <> ?", @newsletter.id).each(&:destroy)
    redirect_to :back
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def index
    @upcoming_service = UpcomingService.next
    @events = Event.upcoming
  end
end

app/controllers/social_justice_newsletters_controller.rb
class SocialJusticeNewslettersController < ApplicationController
  before_filter :authenticate_user!, :only => [:create]

  def index
    @newsletter = SocialJusticeNewsletter.first
    send_data(@newsletter.data, filename: @newsletter.filename,
              type: @newsletter.content_type, disposition: "inline")
  end

  def create
    return if params[:newsletter].blank?

    @newsletter = SocialJusticeNewsletter.new
    @newsletter.file = params[:newsletter]

    @newsletter.save!

    SocialJusticeNewsletter.where("id <> ?", @newsletter.id).each(&:destroy)
    redirect_to :back
  end
end

app/controllers/upcoming_services_controller.rb
class UpcomingServicesController < ApplicationController
  before_filter :authenticate_user!
  def create
    @upcoming_service = UpcomingService.new(params[:upcoming_service])
    @upcoming_service.save!

    redirect_to :back
  end

  def update
    @upcoming_service = UpcomingService.find(params[:id])
    @upcoming_service.update_attributes(params[:upcoming_service])
    redirect_to :back
  end

  def destroy
    UpcomingService.destroy(params[:id])
    redirect_to :back
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/index.html.haml
#add-event.reveal-modal
  %h1 Add an Event
  = simple_form_for @event do |f|
    = f.input :date, label: "Date of event"
    = f.input :time, label: "Time of event"
    = f.input :name, label: "Name of event"
    = f.input :description, label: "Description of event"
    = f.submit "Save"

#add-service.reveal-modal
  %h1 Add an Upcoming Service Description
  = simple_form_for @upcoming_service do |f|
    = f.input :date, label: "Date of the service"
    = f.input :title, label: "Title of the service"
    = f.input :description, label: "Description of the service"
    = f.submit "Save"

.container.wrapper
  .row
    .twelve.columns
      %p= "Logged in as: #{current_user.email}"

.container.wrapper
  .row
    .twelve.columns
      %h3 Upload Newsletter
      = form_tag newsletters_path, multipart: true do
        = file_field_tag "newsletter"
        = submit_tag "Upload"

.container.wrapper
  .row
    .twelve.columns
      %h3 Upload Social Justice News
      = form_tag social_justice_newsletters_path, multipart: true do
        = file_field_tag "newsletter"
        = submit_tag "Upload"

.container.wrapper
  .row
    .twelve.columns
      %h3 Upcoming Services
      %table
        %thead
          %td Date
          %td(colspan="3") Title/Description
        %tbody
          - @upcoming_services.each do |upcoming_service|
            %tr
              = simple_form_for upcoming_service do |f|
                %td= f.input :date, label: false
                %td
                  = f.input :title, label: false
                  = f.input :description, label: false
                %td= f.submit "Update"
                %td= link_to "Delete", upcoming_service, method: :delete
      = link_to "Add New Service", "#", class: "nice large custom button", "data-reveal-id" => "add-service"

.container.wrapper
  .row
    .twelve.columns
      %h3 Upcoming Events
      %table
        %thead
          %td Date/Time
          %td(colspan="3") Title/Description
        %tbody
          - @events.each do |event|
            %tr
              = simple_form_for event do |f|
                %td
                  = f.input :date, label: false
                  = f.input :time, label: false
                %td
                  = f.input :name, label: false
                  = f.input :description, label: false
                %td= f.submit "Update"
                %td= link_to "Delete", event, method: :delete
      = link_to "Add New Event", "#", class: "nice large custom button", "data-reveal-id" => "add-event"

.container.wrapper
  .row
    .twelve.columns
      %h3 Update Calendar
      = simple_form_for @calendar do |f|
        = f.input :data, label: "Paste embedding code here"
        = f.submit "Save"

app/views/calendars/index.html.haml
!!! 5
:plain
  <!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
  <!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
  <!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
  <!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
  <!--[if gt IE 8]><!--> <html lang="en"> <!--<![endif]-->
%head
  %meta(charset="utf-8")

  = stylesheet_link_tag :application
  = csrf_meta_tags

%body
  = render "layouts/flash", {flash: flash}
  %br
  %br
  .container.wrapper
    .row
      .twelve.columns
        %center
          != @calendar.data
  = javascript_include_tag :application

app/views/layouts/_flash.html.haml
- flash.each do |key, msg|
  %div(id = "#{key}")
    %p(style="float:right")
      = link_to_function "X", "Effect.Fade('#{key}')"
    %p= msg
    .clear

app/views/layouts/_footer.html.haml
.container.footer
  .row
    .twelve.columns
      %img(src="assets/logo.png")
  .row
    .twelve.columns
      %a(href="http://www.uua.org/lgbt/welcoming/index.shtml")
        %img(src="assets/welcoming_congregation.jpg")
      %a(href="http://www.uua.org/environment/sanctuary/index.shtml")
        %img(src="assets/green_sanctuary.png")
      %img(src="assets/listen.png")
      %a(href="http://www.standingonthesideoflove.org/")
        %img(src="assets/standing.png")
      %a(href="http://www.uusc.org/")
        %img(src="assets/uusc.png")
      %a(href="http://www.facebook.com/UUFoM")
        %img(src="assets/facebook.jpg")
      %a(href="http://github.com/uufom/uufom")
        %img(src="assets/github.png")
  .row
    .twelve.columns
      :markdown
        &copy; 2012 Unitarian Universalist Fellowship of Midland

app/views/layouts/_header.html.haml
.container.shadowed
  .row.header
    .seven.columns.left-justified
      %h1 Unitarian Universalist Fellowship of Midland
      :markdown
        _A liberal religious haven that cherishes the exploring mind and
        welcomes all souls._
    .five.columns.right-justified
      :markdown
        6220 Jefferson Ave, Midland, MI 48640-2934  
        (989) 631-1162  
        [uufom@uufom.org](mailto:uufom@uufom.org)
  .row.navigation
    #main-cell.two.columns.active
      %a#main(href="#") Home
    #who-we-are-cell.two.columns
      %a#who-we-are(href="#") Who We Are
    #gather-with-us-cell.two.columns
      %a#gather-with-us(href="#") Gather With Us
    #learn-with-us-cell.two.columns
      %a#learn-with-us(href="#") Learn With Us
    #serve-with-us-cell.two.columns
      %a#serve-with-us(href="#") Serve With Us
    #visit-us-cell.two.columns
      %a#visit-us(href="#") Visit Us

app/views/layouts/admin.html.haml
!!! 5
:plain
  <!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
  <!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
  <!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
  <!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
  <!--[if gt IE 8]><!--> <html lang="en"> <!--<![endif]-->
%head
  %meta(charset="utf-8")

  = stylesheet_link_tag :application
  = csrf_meta_tags

%body
  = render "layouts/flash", {flash: flash}
  = yield
  = javascript_include_tag :application

app/views/layouts/public.html.haml
!!! 5
:plain
  <!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
  <!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
  <!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
  <!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
  <!--[if gt IE 8]><!--> <html lang="en"> <!--<![endif]-->
%head
  %meta(charset="utf-8")
  %meta(name="viewport" content="width=device-width")
  %meta(name="apple-mobile-web-app-status-bar-style" content="black")

  %link(rel="apple-touch-icon" href="apple-touch-icon.png")
  %link(rel="icon" type="image/ico" href="favicon.ico")

  = stylesheet_link_tag :application
  = csrf_meta_tags

  /[if lt IE 9]
    = stylesheet_link_tag :ie
    = javascript_include_tag "http://html5shiv.googlecode.com/svn/trunk/html5.js"

  /[if IE]
    :css
      .timer { display: none !important; }
        div.caption { background:transparent; filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=#99000000,endColorstr=#99000000);zoom: 1; }
  
%body
  = render partial: "layouts/header"

  = yield

  = render partial: "layouts/footer"

  = javascript_include_tag :application